### PR TITLE
Fix for ruby 3.3.0

### LINKED ISSUE #4: ruby 3.3.0 'incompatible marshal file format` errors
Four of the tests fail in ruby 3.3.0 (although they work in 3.2.2) with an `incompatible marshal file format` error, even after updating gem dependencies:
```
Finished in 5.32 seconds (files took 0.04708 seconds to load)
25 examples, 4 failures

Failed examples:

rspec ./spec/safe_ruby_spec.rb:5 # SafeRuby#eval allows basic operations
rspec ./spec/safe_ruby_spec.rb:10 # SafeRuby#eval returns correct object
rspec ./spec/safe_ruby_spec.rb:46 # SafeRuby#eval options timeout defaults to a 5 second timeout
rspec ./spec/safe_ruby_spec.rb:53 # SafeRuby#eval options timeout allows custom timeout
```

Here is the first one:

```
  1) SafeRuby#eval allows basic operations
     Failure/Error: raise data

     RuntimeError:
       /var/folders/cy/7pf5w_mj4fg3n6hzjxjs01mr0000gn/T/saferuby20240215-86452-xokox4:17:in `undef_method': undefined method `new' for class `String' (NameError)

           klass.send(:undef_method, method)
                ^^^^^
       Did you mean?  next
       	from /var/folders/cy/7pf5w_mj4fg3n6hzjxjs01mr0000gn/T/saferuby20240215-86452-xokox4:17:in `block in keep_methods'
       	from /var/folders/cy/7pf5w_mj4fg3n6hzjxjs01mr0000gn/T/saferuby20240215-86452-xokox4:16:in `each'
       	from /var/folders/cy/7pf5w_mj4fg3n6hzjxjs01mr0000gn/T/saferuby20240215-86452-xokox4:16:in `keep_methods'
       	from /var/folders/cy/7pf5w_mj4fg3n6hzjxjs01mr0000gn/T/saferuby20240215-86452-xokox4:37:in `<main>'
     # ./lib/safe_ruby/runner.rb:45:in `rescue in eval'
     # ./lib/safe_ruby/runner.rb:41:in `eval'
     # ./lib/safe_ruby/runner.rb:20:in `eval'
     # ./spec/safe_ruby_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # TypeError:
     #   incompatible marshal file format (can't be read)
     #   	format version 4.8 required; 47.118 given
     #   ./lib/safe_ruby/runner.rb:42:in `eval'
```

### PR DESCRIPTION
**Pull request by mattlindsey**
Fixes #4 

Commenting out line 45 in `method_whitelist.rb` fixes the problem, but I don't understand enough to know if that is a valid fix.  
It may certainly break something, so does anyone have any ideas?

Also, I just tried other examples like `SafeRuby.eval('system("rm *")')` and seem to still be getting the `marshal file` error, so it might be a different problem...

### CODE REVIEW

**Comment by andreibondarev** [comment]
@theycallmeswift Do you have merge authority to the repo? :)

**Comment by mattlindsey** [comment]
There are still issues since following test works for ruby 2.x.x but gives `marshal file` error in > 3.0.0:
```ruby
expect(SafeRuby.eval("x = String.new('zzz')")).to eq 'zzz'
```

**Comment by ukutaht** [comment]
Sorry all, I'm not really maintaining this library anymore. Happy to transfer it to someone else who would take better care of it :)

**Comment by ukutaht** [comment]
Alternatively, feel free to fork

**Comment by ausangshukla** [comment]
Changes required to make this work.

1. Fork and Change all Marshal to YAML
2. Add this in an initializer
```
module YAML
    class << self
      alias_method :load, :unsafe_load
    end
end

```

It will work

**Comment by merefield** [comment]
@ausangshukla have to disagree.

Marshall is working fine for me under Ruby `3.3.0` and `3.3.2`.

I have pulled this code into my own library folder and run the specs, and they all pass.

the existing changes in this PR seem at a glance to be sufficient.

It would be great if someone had the bandwidth to take this over and add a tests workflow as it's hard to keep track of changes versus test success.

**Comment by jeromeag** [comment]
I have forked on [gitlab/defmastership](https://gitlab.com/defmastership/safe_ruby) with a mirror on [github](https://github.com/jeromeag/safe_ruby)
- merged https://github.com/mattlindsey/safe_ruby/tree/update-deps to fix issue #4
- add a GitLab CI/CD (I don't know GitHub actions, and i'm fluent with Gitlab CICD :) )
- add some rubocop inspection and most rubocop remarks fixes.

I agree to take the lead on this Gem... and push a fixed 1.0.5 on rubygems.org

@ukutaht let me know if you agree.
